wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.10
    cli_version: 0.18.3
    framework: huggingface
    huggingface_version: 4.44.0.dev0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1731785551
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      - 100
      - 105
      3:
      - 4
      - 13
      - 23
      - 42
      - 55
      4: 3.11.10
      5: 0.18.3
      6: 4.44.0.dev0
      8:
      - 5
      13: linux-x86_64
